# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SNSubspecTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

pod "SNSpec",:subspecs => ['SNOrderPage', 'SNDetialPage'], :path => "../" #.表示同级；../ 表示上一级
#   pod 'SNSpec', :subspecs => ['SNSubspec', 'SNDetialPage'], :git => 'https://github.com/lizhi0123/SNSubspecTest.git', :branch => 'master'
   
   pod 'MGJRouter', '~> 0.9.3'

   

end
