# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SNSubspecTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SNSubspecTest
#   pod "SNSpec/SNSubspec", :path => "../"
#   pod "SNSpec/SNDetialPage", :path => "../"

   
   pod 'SNSpec', :subspecs => ['SNSubspec', 'SNDetialPage'], :git => 'https://github.com/lizhi0123/SNSubspecTest.git', :branch => 'master'
   
   pod 'AFNetworking', '~> 3.1.0'

   

end
